# Generated by Django 5.2.7 on 2025-10-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.student')),
            ],
            options={
                'db_table': 'Attendance',
                'ordering': ['attendance_date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'attendance_date'), name='unique_attendance_date_per_student')],
            },
        ),
    ]
