# Generated by Django 5.2.7 on 2025-10-29 19:21

import datetime
import django.core.validators
import django.db.models.deletion
import stu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code', models.CharField(default=stu.models.generate_code, max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only digits are allowed.')])),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_registration', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(max_length=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
            options={
                'db_table': 'Student',
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'doctor'), name='student_per_doctor', violation_error_message='Student with this first and last name already exists for this doctor')],
            },
        ),
    ]
