# Generated by Django 5.2.7 on 2025-10-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
