# Generated by Django 5.2.7 on 2025-11-01 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only digits are allowed.')]),
        ),
    ]
