# Generated by Django 5.2.7 on 2025-11-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_alter_student_age_alter_student_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='memorization_method',
            field=models.CharField(choices=[('chapter', 'Chapter'), ('eighth', 'Eighth')], default='chapter', max_length=7),
        ),
    ]
