# Generated by Django 5.2.7 on 2025-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('stu', '0006_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='Student_first_n_f17196_idx'),
        ),
    ]
