# Generated by Django 5.2.7 on 2025-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_payment_year_alter_payment_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='code',
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
