# Generated by Django 5.2.7 on 2025-11-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_remove_payment_code_payment_id'),
        ('stu', '0006_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('student', 'month', 'year'), name='unique_payment_per_student_per_month_year'),
        ),
    ]
