# Generated by Django 5.2.7 on 2025-11-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('pay', '0004_payment_unique_payment_per_student_per_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.doctor'),
            preserve_default=False,
        ),
    ]
