"""
Django settings for tar project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import string
import os
import dotenv

dotenv.load_dotenv()

# My Settings


JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
GOOGLE_EMAIL_SENDER = os.getenv("GOOGLE_EMAIL_SENDER")
SMTP_APP_PASSWORD = os.getenv("SMTP_APP_PASSWORD")
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = os.getenv("SMTP_PORT")
ENV = os.getenv("ENVIRONMENT", "production")
TOKEN_ACCESS_NAME = os.getenv("TOKEN_ACCESS_NAME")
TOKEN_REFRESH_NAME = os.getenv("TOKEN_REFRESH_NAME")
TOKEN_ACCESS_LIFETIME = os.getenv("TOKEN_ACCESS_LIFETIME", 15)
TOKEN_REFRESH_LIFETIME = os.getenv("TOKEN_REFRESH_LIFETIME", 60 * 24 * 7)

POLICY = {
    "min_length": 8,
    "max_length": 128,
    "require_upper": True,
    "require_lower": True,
    "require_digit": True,
    "require_special": False,
    "special_chars": string.punctuation,
    "common_passwords": {
        "password",
        "123456",
        "qwerty",
        "abc123",
        "letmein",
        "admin",
        "welcome",
    },
    "max_consecutive": 4,
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["*"]  # broadened for initial deployment; restrict later

# Render.com specific host injection
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    # Ensure Django accepts the external hostname
    ALLOWED_HOSTS = list({*ALLOWED_HOSTS, RENDER_EXTERNAL_HOSTNAME})


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "rest_framework",
    "drf_standardized_errors",
    "api.apps.ApiConfig",
    "stu.apps.StuConfig",
    "att.apps.AttConfig",
    "chap.apps.ChapConfig",
    "pay.apps.PayConfig",
    "eig.apps.EigConfig",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.authentication.AuthenticationMiddleware",
]

ROOT_URLCONF = "tar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "tar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Allow overriding sqlite path (for Render persistent disk mount)
SQLITE_PATH = os.getenv("SQLITE_PATH")
if SQLITE_PATH:
    DATABASES["default"]["NAME"] = SQLITE_PATH


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",  # only JSON
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

DRF_STANDARDIZED_ERRORS = {
    "EXCEPTION_FORMATTER_CLASS": "api.exceptions.MyExceptionFormatter"
}

SPECTACULAR_SETTINGS = {
    "TITLE": "The Circle of Light API",
    "DESCRIPTION": "The Circle of Light description",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
