# Generated by Django 5.2.7 on 2025-11-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stu', '0006_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Quarter',
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_quarter_code', violation_error_message='Quarter with this code already exists')],
            },
        ),
        migrations.CreateModel(
            name='CompletedQuarter',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('progress', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quarters', to='stu.student')),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_by_students', to='eig.quarter')),
            ],
            options={
                'verbose_name': 'Completed Quarter',
                'verbose_name_plural': 'Completed Quarters',
                'db_table': 'CompletedQuarter',
                'ordering': ['-completion_date'],
            },
        ),
    ]
