# Generated by Django 5.2.7 on 2025-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedquarter',
            name='code',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
