# Generated by Django 5.2.7 on 2025-11-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eig', '0002_alter_completedquarter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedquarter',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarters', to='eig.quarter'),
        ),
    ]
