# Generated by Django 5.2.7 on 2025-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eig', '0003_alter_completedquarter_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquarter',
            name='eighth_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedquarter',
            name='hizb_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedquarter',
            name='is_hizb_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completedquarter',
            name='next_eighth_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedquarter',
            name='next_hizb_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedquarter',
            name='quick_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='completedquarter',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
