# Generated by Django 5.2.7 on 2025-11-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eig', '0004_completedquarter_eighth_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquarter',
            name='session_type',
            field=models.CharField(choices=[('memorization', 'Memorization'), ('review', 'Review')], default='review', help_text='Type of session: memorization or review', max_length=20),
        ),
    ]
