# Generated by Django 5.2.7 on 2025-10-30 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('code', models.IntegerField(auto_created=True, max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(114)])),
                ('name', models.CharField(max_length=50)),
                ('number_of_verses', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)])),
            ],
            options={
                'db_table': 'Chapter',
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_chapter_code', violation_error_message='Chapter with this code already exists')],
            },
        ),
    ]
