# Generated by Django 5.2.7 on 2025-10-30 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(114)]),
        ),
    ]
