# Generated by Django 5.2.7 on 2025-11-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0002_alter_chapter_code'),
        ('stu', '0006_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedChapter',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('progress', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by_students', to='chap.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_chapters', to='stu.student')),
            ],
            options={
                'verbose_name': 'Completed Chapter',
                'verbose_name_plural': 'Completed Chapters',
                'db_table': 'CompletedChapter',
                'ordering': ['-completion_date'],
            },
        ),
    ]
