# Generated by Django 5.2.7 on 2025-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0003_completedchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedchapter',
            name='code',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='completedchapter',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
