# Generated by Django 5.2.7 on 2025-11-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0004_alter_completedchapter_code_and_more'),
    ]

    operations = [
    ]
