# Generated by Django 5.2.7 on 2025-11-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0005_auto_detect_changes'),
    ]

    operations = [
    ]
