# Generated by Django 5.2.7 on 2025-11-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chap", "0006_auto_detect_changes"),
        ("stu", "0006_student_created_at_student_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedchapter",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="completedchapter",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="completedchapter",
            constraint=models.UniqueConstraint(
                fields=("created_at", "chapter", "student"),
                name="unique_chapter_completion_per_student_date",
                violation_error_message="This student already has this chapter going through on this date",
            ),
        ),
    ]
