# Generated by Django 5.2.7 on 2025-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0007_alter_completedchapter_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='completedchapter',
            name='unique_chapter_completion_per_student_date',
        ),
    ]
