# Generated by Django 5.2.7 on 2025-11-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0008_remove_completedchapter_unique_chapter_completion_per_student_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_by_students', to='chap.chapter'),
        ),
    ]
