# Generated by Django 5.2.7 on 2025-11-05 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0009_alter_completedchapter_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedchapter',
            name='is_surah_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='next_surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_next_surahs', to='chap.chapter'),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='next_verse_from',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='next_verse_to',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='quick_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_surahs', to='chap.chapter'),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='verse_from',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='completedchapter',
            name='verse_to',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
