# Generated by Django 5.2.7 on 2025-11-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chap', '0012_completedchapter_session_type'),
    ]

    operations = [
    ]
