# Generated by Django 5.2.7 on 2025-10-29 19:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('code', models.CharField(default=api.models.generate_doctor_code, max_length=12, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Doctor',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
